### ISSUE TITLE
Support for AArch64- and Linux-specific protection attributes

### ISSUE THREAD

**Issue by akirilov-arm** [darfink/region-rs#21]
Since version 5.10 Linux [defines](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/arm64/include/uapi/asm/mman.h?h=v5.10.113#n7) a couple of AArch64-specific access flags - `PROT_BTI` for pages guarded by the Branch Target Identification technology and `PROT_MTE` for pages to which the Memory Tagging Extension applies. Currently (as of commit 5087445) there is no way to use these attributes with the `Protection` struct even via the `Protection::from_bits_unchecked()` method because the implementation [ignores](https://github.com/darfink/region-rs/blob/5087445f08b3f78c481fb8cde18b47bb67d5eb22/src/os/unix.rs#L70) any unknown values right before the call to `mprotect()`, for example.

**Comment by darfink** [comment]
That's a very valid use case.

I've pushed a commit that aligns the protection constants to their UNIX counterparts (this was always the intention, but they had been accidentally unaligned) & maps directly to an integer (commit: https://github.com/darfink/region-rs/commit/03fd93c3ae23e197775576a4fe170d29f4e06ffc).

Will be part of release 3.0.1
